In [2]:
import torch
import numpy as np
import pandas as pd
from vit_pytorch import ViT
from dataloader import testing_dataset
from util import util
from torch.nn.functional import sigmoid
from torch.utils.data import Dataset, DataLoader

In [3]:
torch.cuda.is_available()

True

In [4]:
dataset = DataLoader(testing_dataset, shuffle=True)

In [5]:
vision_model = ViT(
    image_size=128 * 3,
    patch_size=32,
    num_classes=29,
    dim=512,
    depth=6,
    heads=16,
    mlp_dim=1024,
    dropout = 0.1,
    emb_dropout = 0.1
).to('cuda')


In [6]:
model_dict = torch.load('saves/V1-Final/model_epoch_10.pth')
model_dict.keys()

dict_keys(['epoch', 'model_state_dict', 'optimizer_state_dict', 'loss', 'testing_loss'])

In [7]:
vision_model.load_state_dict(model_dict['model_state_dict'])
vision_model.eval();

In [8]:
sample = next(iter(dataset))

In [9]:
with torch.no_grad():
    probs = vision_model(sample[0])

In [10]:
probs = sigmoid(probs)
probs

tensor([[0.3272, 0.3556, 0.3311, 0.3283, 0.3404, 0.1802, 0.2589, 0.4617, 0.3035,
         0.3422, 0.1998, 0.2937, 0.2229, 0.1676, 0.1957, 0.2249, 0.2787, 0.2108,
         0.1892, 0.2136, 0.3826, 0.2934, 0.1780, 0.2088, 0.1298, 0.2228, 0.2866,
         0.1773, 0.2132]], device='cuda:0')

In [11]:
sample[1]

tensor([[0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], device='cuda:0')

In [12]:
util.calculate_precession(probs, sample[1])

tensor([-1.5000])

In [13]:
util.to_classes(sample[1])

(['Adult', 'Mature'], [1.0, 1.0])

In [14]:
util.pick_top(probs, 2, prettify=True)

(['Drama', 'Wuxia'], [0.4616779088973999, 0.3825852870941162])