In [1]:
from architecture import pipe
from PIL import Image
from dataloader import testing_dataset
from util import util
from torch.utils.data import DataLoader
import torch
from torch.nn import BCELoss

D:\ml\mtest\learn_env\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
D:\ml\mtest\learn_env\lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
D:\ml\mtest\learn_env\lib\site-packages\huggingface_hub\file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(


In [2]:
state = torch.load('./saves/exp_5/model_epoch_3.pth')

In [3]:
pipe.model.load_state_dict(state['model_state_dict'])
pipe.model = pipe.model.eval()

In [4]:
dataset = DataLoader(testing_dataset, shuffle=True)

In [5]:
sample = next(iter(dataset))

In [6]:
# util.to_pil(sample[0][0])

In [7]:
print(sample[1])
util.to_classes(sample[1])

tensor([[1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
         0., 0., 0., 0., 0., 0., 0., 1.]], device='cuda:0')


(['adventure', 'action', 'seinen', 'wuxia'], [1.0, 1.0, 1.0, 1.0])

In [8]:
res = pipe.pipe(sample[0])
res

D:\ml\mtest\learn_env\lib\site-packages\diffusers\models\attention_processor.py:1259: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at ..\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:455.)
  hidden_states = F.scaled_dot_product_attention(


tensor([[0.6626, 0.4890, 0.5356, 0.3020, 0.6377, 0.6147, 0.4194, 0.2715, 0.4260,
         0.4480, 0.3789, 0.6431, 0.2773, 0.5293, 0.4429, 0.3345, 0.4270, 0.4983,
         0.4988, 0.4507, 0.3999, 0.2583, 0.5405, 0.4619, 0.3015, 0.4531]],
       device='cuda:0', dtype=torch.float16, grad_fn=<SigmoidBackward0>)

In [9]:
util.pick_top(res[0], 6, prettify=True)

(['action', 'martial arts', 'drama', 'ecchi', 'slice of life', 'adventure'],
 [0.66259765625,
  0.64306640625,
  0.6376953125,
  0.61474609375,
  0.54052734375,
  0.53564453125])

In [21]:
util.calculate_precession(res, sample[1], cutoff=.65)

tensor([0.2500])